name: RSRM  # Change to your preferred environment name
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9  # Or another version if needed
  - pip
  - pip:
      - deap==1.3.3
      - numpy==1.21.5
      - pandas==1.4.1
      - scipy==1.8.0
      - sympy==1.10.1

